---
- name: Dock - Set screen edge orientation
  community.general.osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: "{{ setup_macos_dock_orientation | default('bottom') }}"
    state: present
  notify: Restart Dock

- name: Dock - Set tile icon size
  community.general.osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: int
    value: "{{ setup_macos_dock_tilesize | default(48) }}"
    state: present
  notify: Restart Dock

- name: Dock - Set autohide behavior
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: "{{ setup_macos_dock_autohide | default(false) }}"
    state: present
  notify: Restart Dock

- name: Dock - Disable MRU spaces reordering
  community.general.osx_defaults:
    domain: com.apple.dock
    key: mru-spaces
    type: bool
    value: false
    state: present
  notify: Restart Dock

- name: Dock - Disable recent applications in Dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: show-recents
    type: bool
    value: "{{ setup_macos_dock_show_recents | default(false) }}"
    state: present
  notify: Restart Dock

- name: Dock - Minimize windows into application icon
  community.general.osx_defaults:
    domain: com.apple.dock
    key: minimize-to-application
    type: bool
    value: true
    state: present
  notify: Restart Dock

