---
- name: Git - Set global user name
  community.general.git_config:
    name: user.name
    value: "{{ setup_macos_git_user_name }}"
    scope: global
  when: setup_macos_git_user_name | default('') | length > 0

- name: Git - Set global user email
  community.general.git_config:
    name: user.email
    value: "{{ setup_macos_git_user_email }}"
    scope: global
  when: setup_macos_git_user_email | default('') | length > 0

- name: Git - Set global default branch
  community.general.git_config:
    name: init.defaultBranch
    value: "{{ setup_macos_git_default_branch | default('main') }}"
    scope: global

